{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rgw-exporter.serviceAccountName" . }}
  labels:
    {{- include "rgw-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  namespace: {{ .Values.namespace | default .Chart.Name }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
